Repository din0s/ActionHeroes, pull requests merged in 2020-06, with the labels that each got.

#43 Team creation
  package-lock.json
  package.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.scss
  src/www/components/actioncard/action.json
  src/www/components/popup/Popup.scss
  src/www/components/popup/TeamPopup.jsx
  src/www/containers/actionspage/actions.json
  src/www/containers/actionspage/categories.json
  src/www/containers/contactpage/ContactPage.jsx
  src/www/containers/landingpage/categories.json
  src/www/containers/teamprofile/team.json
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/containers/teamspage/TeamsPage.scss
  src/www/containers/teamspage/categories.json
  src/www/containers/teamspage/teams.json
  src/www/containers/userprofile/actionsAttended.json
  src/www/containers/userprofile/actionsOrganized.json
  src/www/containers/userprofile/teamsFollow.json
Labels: enhancement

#42 Dashboard
  package-lock.json
  package.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/UserController.js
  src/api/index.js
  src/www/App.js
  src/www/actions/auth.js
  src/www/components/routes/GuestRoute.jsx
  src/www/components/routes/PrivateRoute.jsx
  src/www/components/routes/Routes.jsx
  src/www/components/selector/Selector.jsx
  src/www/containers/authentication/Login.jsx
  src/www/containers/authentication/Signup.jsx
  src/www/containers/dashboard/Dashboard.jsx
  src/www/containers/dashboard/Dashboard.scss
  src/www/containers/dashboard/dashboard.json
  src/www/containers/userprofile/UserProfile.js
  src/www/i18n.js
Labels: enhancement

#53 API: Update team
  src/api/controllers/TeamController.js
  src/api/middleware/check-owner.js
  src/api/models/TeamModel.js
Labels: enhancement

#49 API: Update action
  src/api/CustomError.js
  src/api/controllers/ActionController.js
  src/api/middleware/check-admin.js
  src/api/middleware/check-permissions.js
  src/api/middleware/extract-team.js
  src/api/models/ActionModel.js
  src/api/routes/action.js
Labels: enhancement

#44 Settings page
  package-lock.json
  package.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/actions/index.js
  src/www/actions/profile.js
  src/www/components/map/Map.jsx
  src/www/components/map/Map.scss
  src/www/components/navbar/member_nav/MemberNav.js
  src/www/components/routes/Routes.jsx
  src/www/containers/settingspage/SettingsPage.jsx
  src/www/containers/settingspage/SettingsPage.scss
  src/www/containers/settingspage/categories.json
  src/www/containers/settingspage/favouriteCategories.json
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/UserProfile.scss
  src/www/reducers/auth.js
Labels: enhancement

#55 API: Team followers
  src/api/controllers/TeamUserController.js
  src/api/models/TeamModel.js
  src/api/models/UserModel.js
  src/api/routes/team.js
Labels: enhancement

#56 Better handling of the authentication handshake
  package-lock.json
  package.json
  src/www/App.js
  src/www/actions/auth.js
  src/www/components/routes/GuestRoute.jsx
  src/www/components/routes/PrivateRoute.jsx
  src/www/containers/spinner/SpinnerPage.jsx
  src/www/containers/spinner/SpinnerPage.scss
  src/www/reducers/auth.js
Labels: bug, enhancement

#57 API: Delete Action/Team implementation
  src/api/controllers/ActionController.js
  src/api/controllers/ActionUserController.js
  src/api/controllers/TeamController.js
  src/api/controllers/TeamUserController.js
  src/api/models/ActionModel.js
  src/api/models/UserModel.js
  src/api/routes/action.js
  src/api/routes/team.js
Labels: enhancement

#54 Dynamically fetch categories from the API
  app.json
  package.json
  scripts/categories.js
  scripts/populate-categories.js
  src/api/controllers/CategoryController.js
  src/api/index.js
  src/api/models/CategoryModel.js
  src/api/routes/category.js
  src/www/App.js
  src/www/actions/categories.js
  src/www/actions/index.js
  src/www/components/filterlist/FilterList.jsx
  src/www/components/popup/TeamPopup.jsx
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/actionspage/categories.json
  src/www/containers/settingspage/SettingsPage.jsx
  src/www/containers/settingspage/categories.json
  src/www/containers/settingspage/favouriteCategories.json
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/containers/teamspage/categories.json
  src/www/reducers/categories.js
  src/www/reducers/index.js
Labels: enhancement

#58 API: Image uploading & update profile implementation
  package-lock.json
  package.json
  public/img/profile/default.png
  public/img/profile/profilePhoto.jpg
  src/api/controllers/ActionController.js
  src/api/controllers/ImageController.js
  src/api/controllers/TeamController.js
  src/api/controllers/UserController.js
  src/api/index.js
  src/api/middleware/upload.js
  src/api/models/ActionModel.js
  src/api/models/ImageModel.js
  src/api/models/TeamModel.js
  src/api/models/UserModel.js
  src/api/routes/action.js
  src/api/routes/image.js
  src/api/routes/team.js
  src/api/routes/user.js
  src/www/actions/profile.js
  src/www/components/popup/TeamPopup.jsx
  src/www/containers/settingspage/SettingsPage.jsx
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/UserProfile.scss
Labels: enhancement

#63 Recreation Of Map Component
  package-lock.json
  package.json
  src/www/components/map/Map.jsx
  src/www/containers/settingspage/SettingsPage.jsx
Labels: enhancement

#62 Implement dashboard API & make frontend container dynamic
  public/img/actionprofile/default.jpg
  public/img/teaminfo/default.png
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/UserController.js
  src/api/routes/user.js
  src/www/containers/dashboard/Dashboard.jsx
  src/www/containers/dashboard/Dashboard.scss
  src/www/containers/dashboard/dashboard.json
Labels: enhancement

#59 API: Get actions & teams
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/ActionController.js
  src/api/controllers/TeamController.js
  src/api/middleware/check-auth-optional.js
  src/api/models/ActionModel.js
  src/api/models/TeamModel.js
  src/api/routes/action.js
  src/api/routes/team.js
  src/www/App.scss
  src/www/components/pagination/Pagination.jsx
  src/www/components/routes/Routes.jsx
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionprofile/ActionProfile.scss
  src/www/containers/actionprofile/action.json
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/actionspage/ActionsPage.scss
  src/www/containers/actionspage/actions.json
  src/www/containers/dashboard/Dashboard.scss
  src/www/containers/teamprofile/TeamProfile.jsx
  src/www/containers/teamprofile/TeamProfile.scss
  src/www/containers/teamprofile/team.json
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/containers/teamspage/TeamsPage.scss
  src/www/containers/teamspage/teams.json
Labels: enhancement

#64 Connected profile with backend
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/UserController.js
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/actionsAttended.json
  src/www/containers/userprofile/actionsOrganized.json
  src/www/containers/userprofile/teamsFollow.json
  src/www/containers/userprofile/teamsOwned.json
Labels: enhancement

#65 Fix duplicate declaration for imports & dump/restore scripts
  package.json
  src/api/controllers/UserController.js
Labels: bug

#67 Resolving Issues about social media
  public/img/social_media/facebook.svg
  public/img/social_media/github.svg
  public/img/social_media/instagram.svg
  public/img/social_media/linkedin.svg
  public/img/social_media/twitter.svg
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/App.scss
  src/www/components/footer/Footer.js
  src/www/components/footer/Footer.scss
  src/www/containers/authentication/Authentication.scss
  src/www/containers/authentication/Login.jsx
  src/www/containers/authentication/Signup.jsx
  src/www/containers/landingpage/LandingPage.jsx
  src/www/containers/landingpage/LandingPage.scss
Labels: enhancement

#52 Create Action
  package-lock.json
  package.json
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/ActionController.js
  src/api/controllers/TeamController.js
  src/api/controllers/UserController.js
  src/www/App.scss
  src/www/actions/action.js
  src/www/actions/index.js
  src/www/actions/team.js
  src/www/components/actioncard/ActionCard.jsx
  src/www/components/actioncard/ActionCard.scss
  src/www/components/actioncard/action.json
  src/www/components/loader/Loader.jsx
  src/www/components/map/Map.jsx
  src/www/components/popup/ActionPopup.jsx
  src/www/components/popup/Popup.scss
  src/www/components/popup/TeamPopup.jsx
  src/www/components/selector/Selector.jsx
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionprofile/ActionProfile.scss
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/actionspage/ActionsPage.scss
  src/www/containers/dashboard/Dashboard.jsx
  src/www/containers/spinner/SpinnerPage.jsx
  src/www/containers/spinner/SpinnerPage.scss
  src/www/containers/teamprofile/TeamProfile.jsx
  src/www/containers/teamprofile/TeamProfile.scss
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/UserProfile.scss
  src/www/reducers/auth.js
  src/www/vars.scss
Labels: enhancement

#69 Updated joinUser to return photo
  src/api/controllers/UserController.js
Labels: bug

#68 Edit Team Button
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/actions/action.js
  src/www/actions/team.js
  src/www/components/popup/ActionPopup.jsx
  src/www/components/popup/Popup.scss
  src/www/components/popup/TeamPopup.jsx
  src/www/containers/teamprofile/TeamProfile.jsx
  src/www/containers/teamprofile/TeamProfile.scss
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/reducers/auth.js
Labels: enhancement

#70 Edit action
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/controllers/ActionController.js
  src/www/components/popup/ActionPopup.jsx
  src/www/components/selector/Selector.jsx
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionspage/ActionsPage.jsx
Labels: enhancement

#72 Visual Changes
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionprofile/ActionProfile.scss
  src/www/containers/actionspage/ActionsPage.scss
  src/www/containers/dashboard/Dashboard.scss
  src/www/containers/userprofile/UserProfile.scss
Labels: enhancement

#71 Standard page height, fix ActionPopup reset, empty category placeholder
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/routes/action.js
  src/www/App.scss
  src/www/components/actioncard/ActionCard.jsx
  src/www/components/footer/Footer.scss
  src/www/components/popup/ActionPopup.jsx
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/actionspage/ActionsPage.scss
  src/www/containers/authentication/Authentication.scss
  src/www/containers/contactpage/ContactPage.scss
  src/www/containers/dashboard/Dashboard.scss
  src/www/containers/landingpage/LandingPage.scss
  src/www/containers/settingspage/SettingsPage.scss
  src/www/containers/teamprofile/TeamProfile.scss
  src/www/containers/userprofile/UserProfile.scss
  src/www/date.js
Labels: bug, enhancement
