Repository din0s/ActionHeroes, pull requests merged in 2020-04, with the labels that each got.

#16 API Logging
  package-lock.json
  package.json
  src/api/index.js
Labels: enhancement

#18 Heroku deployment support for review apps
  Procfile
  app.json
  src/api/index.js
Labels: enhancement

#14 Contact page
  package-lock.json
  package.json
  public/img/bg_contact.png
  public/img/form_img.png
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/components/alert/AlertTemplate.js
  src/www/components/alert/icons/BaseIcon.js
  src/www/components/alert/icons/CloseIcon.js
  src/www/components/alert/icons/ErrorIcon.js
  src/www/components/alert/icons/InfoIcon.js
  src/www/components/alert/icons/SuccessIcon.js
  src/www/containers/contactpage/ContactPage.jsx
  src/www/containers/contactpage/ContactPage.scss
  src/www/vars.scss
Labels: enhancement

#17 Landing page
  .gitignore
  package-lock.json
  package.json
  public/img/KidBackground.png
  public/img/background.jpg
  public/img/community.svg
  public/img/friendship.svg
  public/img/logo.svg
  public/img/organizer.svg
  public/img/smallicon.svg
  public/img/volunteer.svg
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/components/navbar/NavBar.scss
  src/www/containers/landingpage/LandingPage.js
  src/www/containers/landingpage/LandingPage.scss
Labels: enhancement

#25 Add pm2 configuration for production deployment
  bin/prod.sh
  ecosystem.config.js
  package-lock.json
  src/api/index.js
Labels: enhancement

#24 CSS fixes for Landing, Contact & Auth pages + Navbar components
  package-lock.json
  package.json
  public/img/KidBackground.png
  public/img/contact/background.png
  public/img/contact/form_img.png
  public/img/icons/arrow.svg
  public/img/icons/hamburger.svg
  public/img/icons/search.png
  public/img/landing/category.jpg
  public/img/landing/community.svg
  public/img/landing/friendship.svg
  public/img/landing/intro_icon.svg
  public/img/landing/organizer.svg
  public/img/landing/parallax1.jpg
  public/img/landing/parallax2.jpg
  public/img/landing/parallax3.jpg
  public/img/landing/volunteer.svg
  public/index.html
  src/www/App.js
  src/www/components/navbar/NavBar.js
  src/www/components/navbar/NavBar.scss
  src/www/components/navbar/guest_nav/GuestNav.scss
  src/www/components/navbar/language_selector/LanguageSelector.js
  src/www/components/navbar/language_selector/LanguageSelector.scss
  src/www/components/navbar/member_nav/MemberNav.js
  src/www/components/navbar/member_nav/MemberNav.scss
  src/www/components/searchbar/SearchBar.scss
  src/www/containers/authentication/Authentication.scss
  src/www/containers/authentication/Login.jsx
  src/www/containers/authentication/Signup.jsx
  src/www/containers/contactpage/ContactPage.jsx
  src/www/containers/contactpage/ContactPage.scss
  src/www/containers/landingpage/LandingPage.js
  src/www/containers/landingpage/LandingPage.scss
  src/www/containers/landingpage/categories.json
  src/www/index.scss
  src/www/vars.scss
Labels: enhancement

#20 API: Action & team creation
  src/api/controllers/ActionController.js
  src/api/controllers/TeamController.js
  src/api/controllers/UserController.js
  src/api/models/ActionModel.js
  src/api/models/SearchModel.js
  src/api/models/TeamModel.js
  src/api/models/UserModel.js
  src/api/routes/action.js
  src/api/routes/team.js
  src/api/routes/user.js
Labels: enhancement, low priority

#32 Create FilterList component
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/components/filterlist/FilterList.jsx
  src/www/components/filterlist/FilterList.scss
Labels: enhancement

#33 FilterList responsiveness for devices <800px
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/components/filterlist/FilterList.jsx
  src/www/components/filterlist/FilterList.scss
Labels: enhancement

#30 Teams page
  package-lock.json
  package.json
  public/img/teams/team.png
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/components/filterlist/FilterList.scss
  src/www/components/navbar/NavBar.js
  src/www/components/navbar/NavBar.scss
  src/www/components/pagination/Pagination.jsx
  src/www/components/pagination/Pagination.scss
  src/www/components/searchbar/SearchBar.js
  src/www/containers/teamspage/TeamsPage.jsx
  src/www/containers/teamspage/TeamsPage.scss
  src/www/containers/teamspage/categories.json
  src/www/containers/teamspage/teams.json
Labels: enhancement

#23 Profile Page
  public/img/profile/categories.jpg
  public/img/profile/profilePhoto.jpg
  public/img/profile/sky.jpg
  public/img/profile/teams.jpg
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/api/models/CategoryModel.js
  src/api/models/TeamModel.js
  src/api/models/UserModel.js
  src/www/App.js
  src/www/components/navbar/NavBar.js
  src/www/components/navbar/member_nav/MemberNav.js
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/UserProfile.scss
  src/www/containers/userprofile/actions.json
  src/www/containers/userprofile/teams.json
Labels: enhancement

#31 Actions page
  public/img/actions/lime.jpg
  src/www/App.js
  src/www/components/filterlist/FilterList.scss
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/actionspage/ActionsPage.scss
  src/www/containers/actionspage/actions.json
  src/www/containers/actionspage/categories.json
  src/www/containers/contactpage/ContactPage.scss
Labels: enhancement

#34 Team-Info page
  public/img/teaminfo/acm.jpg
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/components/actioncard/ActionCard.jsx
  src/www/components/actioncard/ActionCard.scss
  src/www/components/actioncard/action.json
  src/www/containers/landingpage/LandingPage.jsx
  src/www/containers/teamprofile/TeamProfile.jsx
  src/www/containers/teamprofile/TeamProfile.scss
  src/www/containers/teamprofile/team.json
Labels: enhancement

#35 Action info
  public/img/actionprofile/acm.jpg
  public/img/actionprofile/local-hack-day.jpg
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/App.js
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionprofile/ActionProfile.scss
  src/www/containers/actionprofile/action.json
Labels: enhancement

#38 Code fixes for search, list elements & input fields
  src/www/components/actioncard/ActionCard.jsx
  src/www/components/input/Input.jsx
  src/www/components/navbar/NavBar.js
  src/www/components/searchbar/SearchBar.js
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionspage/ActionsPage.jsx
  src/www/containers/authentication/Login.jsx
  src/www/containers/authentication/Signup.jsx
  src/www/containers/landingpage/LandingPage.jsx
  src/www/containers/teamprofile/TeamProfile.jsx
Labels: bug

#39 Updated translation
  public/locales/el/translation.json
  public/locales/en/translation.json
  src/www/components/actioncard/ActionCard.jsx
  src/www/components/filterlist/FilterList.jsx
  src/www/containers/actionprofile/ActionProfile.js
  src/www/containers/actionprofile/action.json
  src/www/containers/actionspage/actions.json
  src/www/containers/actionspage/categories.json
  src/www/containers/landingpage/categories.json
  src/www/containers/teamprofile/TeamProfile.jsx
  src/www/containers/teamspage/categories.json
  src/www/containers/teamspage/teams.json
  src/www/containers/userprofile/UserProfile.js
  src/www/containers/userprofile/UserProfile.scss
  src/www/containers/userprofile/actionsAttended.json
  src/www/containers/userprofile/actionsOrganized.json
  src/www/containers/userprofile/teamsFollow.json
  src/www/containers/userprofile/teamsOwned.json
  src/www/date.js
Labels: enhancement
